languageCode = "en"
languageName = "English"
weight = 1
title = "Awesome n8n Workflows"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/nenjotech-logo.png"
  description = "Building Smarter Systems"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "Awesome n8n Workflows"
  image = "img/nenjotech-logo.png"
  headline = "\"Welcome to my collection of AI-powered n8n workflows! 🚀\""
  bio = "This project is a curated hub of ready-to-use workflows for AI automation — from simple utilities to more advanced pipelines. Some workflows are built by me, while others are adapted from open-source projects across GitHub (credit goes to the amazing community)"
   links = [
     { github = "https://github.com/nenjotsu/awesome-n8n-workflows" },
   ]
